### ISSUE TITLE
Add missing imports

### ISSUE THREAD

**Issue by seananderson** [sempwn/cr0eso#8]
See `no visible global function definition` warnings on R CMD check.

Also, I wouldn't import the tidyverse, just the specific packages you need.

Don't forget the stats imports:  "quantile", "rpois"

**Comment by sempwn** [comment]
Just to double-check how you're creating that warning? Are you running:
`devtools::check()` ?

**Comment by seananderson** [comment]
Yes, or command-shift-E in RStudio. Or `R CMD check` in the terminal if you want to be old school.
